DO $$
BEGIN
  CREATE TABLE PRODUCT (
    PRODUCT_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
  );

  COMMENT ON  TABLE PRODUCT IS 'Table to store Products';
  COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS 'The Product Id in this table.';
  COMMENT ON COLUMN PRODUCT.NAME IS 'The Name in this table.';
 END
$$;